### ISSUE TITLE
Retornando sempre: processor not found

### ISSUE THREAD

**Issue by joaoneto** [maxipago/PHP-Integration-lib#13]
Olá,

Estou fazendo o teste no endpoint https://testapi.maxipago.net/UniversalAPI/postXML e sempre recebo uma mensagem de erro:
> XML Response: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><api-error><errorCode>1</errorCode><errorMsg><![CDATA[processor not found ]]></errorMsg></api-error>

Estou tirando como base o exemplo de vocês: https://github.com/maxipago/PHP-Integration-lib/blob/master/test/boleto-mandatory.php

Dados enviados:
```php
    $maxiPago = new maxiPago;
    $maxiPago->setCredentials("XXXXX", "XXXXXXXXXXXXXXXXXXXXXXXX");
    $maxiPago->setEnvironment("TEST");
    $maxiPago->setDebug(true);

    $data = array(
      "processorID" => '12',
      "referenceNum" => $pedido_id,
      "chargeTotal" => number_format($valor_total, 2, '.', ''),
      "bname" => $cliente_nome . ' ' . $cliente_sobrenome,
      "number" => $pedido_id,
      "expirationDate" =>  date('Y-m-d', strtotime("+1 days")),
      "instructions" =>  "Não receber após vencimento.;Não receber pagamento com cheque."
    );

    $maxiPago->boletoSale($data);

    if ($maxiPago->isErrorResponse()) {
      echo 'ERRO: ' . $maxiPago->getMessage();
      die;
    } else {
      echo $maxiPago->getBoletoUrl();
      die;
    }
````
Tentei usar o `test/boleto-mandatory.php` e retornou o mesmo erro `processor not found`

**Comment by anestesya** [comment]
Eu também estou tentando e recebo o mesmo erro, você conseguiu descobrir o que gera esse problema?

**Comment by joaoneto** [comment]
@anestesya A conta estava encerrada

**Comment by anestesya** [comment]
Humm, oloko acabei de receber a chave, não acredito que a minha conta já esteja encerrada :P

**Comment by adrianoramos** [comment]
O maxiPago oferece duas chaves, uma para produção e outra para testes. Verifique se você está usando a chave de produção no ambiente no ambiente de teste ou vice-versa.
